#!/bin/bash
set -e

echo "Running devkit puppet module"
rm -rf /tmp/devkit
git clone https://github.com/LandRegistry/infrastructure-puppet-devkit /tmp/devkit
puppet apply /tmp/devkit/tests/optional.pp --modulepath=/tmp

echo "Updating repositories"
apt-get update -qq

echo "Setting up core linux tools"
apt-get install -qy libcurl4-openssl-dev phantomjs
apt-get install -qy binutils libproj-dev gdal-bin libgdal-dev libgeos-3.4.2 libproj0 libgdal1h  python-gdal

echo "setting up mongodb"
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
apt-get update
apt-get install -y mongodb-org


service mongod start

set +o errexit

sudo /etc/init.d/elasticsearch start

echo "Configuring user environment"
WORKON_HOME=/home/vagrant/land-registry-python-venvs
bash_profile=/home/vagrant/.bash_profile
rm -rf ${WORKON_HOME}
mkdir -p ${WORKON_HOME}

echo "Bootstrapping environment"
su vagrant -c cat <<EOF > /home/vagrant/.ssh/config
Host github.com
	StrictHostKeyChecking no 

EOF
chown -R vagrant:vagrant /home/vagrant
su vagrant -c /vagrant/script/bin/lr-bootstrap

cat <<EOF > ${bash_profile}
export WORKON_HOME=${WORKON_HOME}
export PATH=/vagrant/script/bin:${PATH}

source /usr/local/bin/virtualenvwrapper.sh
alias ls="ls -F"
cd /vagrant

if [[ ! -d ./apps ]] ; then
	echo "Bootstrapping environment"
	lr-bootstrap
fi

lr-nginx
EOF

echo "Configuring nginx"
rm -f /tmp/etchosts
/vagrant/script/bin/lr-nginx

echo "Configuring /etc/hosts"
ETCHOSTS=`cat /tmp/etchosts`

cat <<EOF > /etc/hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
0.0.0.0  lr-dev lr-ubuntu
172.16.42.43 ${ETCHOSTS}

EOF

rm -f /tmp/etchosts

# A reminder...
echo "Copying motd"
sudo cp /vagrant/config/motd /etc/motd
